### ISSUE TITLE
pre-liquibase with spring boot DataJpaTest doesn't seem to work

### ISSUE THREAD

**Issue by paul58914080** [lbruun/Pre-Liquibase#2]
How to re-produce ?

1. Create a simple spring boot starter with jpa project (v 2.5.2) (or you can also use the example project)
2. Write a simple jpa test annotated with `@DataJpaTest` and application.yaml with property
```yaml
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        default_schema: EXAMPLE
        show_sql: false
        use_sql_comments: false
        format_sql: false
      org:
        hibernate:
          envers:
            default_schema: EXAMPLE_AUDIT
            store_data_at_delete: true
  liquibase:
    enabled: true
    liquibase-schema: LIQUIBASE
    default-schema: EXAMPLE
 ```

3. When you run a simple boot test, you would notice exception `Schema "LIQUIBASE" not found; SQL statement:`
